coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: false
        target: 100%

parsers:
  javascript:
    enable_partials: yes
