settings:
  react:
    version: detect

env:
  browser: true
  es2021: true

extends:
  - standard
  - plugin:react/recommended

parserOptions:
  ecmaVersion: 17
  sourceType: module

plugins:
  - react

overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
      - "src/setupTests.js"
      - "src/test/wait.js"
    env:
      jest: true

# https://eslint.org/docs/latest/rules/
rules:
  comma-dangle:
    - error
    - always-multiline
  generator-star-spacing: off
  indent: off
  multiline-ternary: off
  no-unused-vars:
    - error
    - varsIgnorePattern: "^_"
      args: none
  quotes:
    - error
    - double
    - avoidEscape: true
  react/display-name: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  space-before-function-paren: off
  semi:
    - error
    - always
  no-var: error
