/* istanbul ignore file */
// .. because this was generated by CRA

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App";
import IncidentManagementSystem from "./ims/IMS";
import reportWebVitals from "./reportWebVitals";

const imsBagURL = "/ims/api/bag";

const ims = new IncidentManagementSystem(imsBagURL);

const container = document.getElementById("root");
const root = createRoot(container);

root.render(
  <StrictMode>
    <App ims={ims} />
  </StrictMode>,
);

reportWebVitals();
