# Docs:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:
    types: [checks_requested]

jobs:
  unit:
    name: Unit Tests

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden CI
        uses: step-security/harden-runner@v2.6.0
        with:
          disable-sudo: true
          disable-file-monitoring: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codecov.io:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          # Disable warnings due to https://github.com/twbs/bootstrap/pull/36258
          CI: "false"

      - name: Run unit tests
        run: npm test -- --ci --watchAll=false --coverage

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
          env_vars: GITHUB_REF,GITHUB_COMMIT,GITHUB_USER,GITHUB_WORKFLOW
          fail_ci_if_error: true
          verbose: true
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_COMMIT: ${{ github.sha }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_WORKFLOW: ${{ github.workflow }}

  docker:
    name: Build Docker image

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: ./bin/build;

      - name: Save Docker image
        run: |
          mkdir images;
          docker image save ranger-ims-web:dev | gzip -6 > images/web.tgz;

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: images

  test-docker:
    name: Test Docker image

    needs: [docker]

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden CI
        uses: step-security/harden-runner@v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: images
          path: images

      - name: Load Docker image
        run: gzip --uncompress --stdout images/web.tgz | docker image load;

      - name: Test Docker image
        run: ./bin/test_docker;
